version: '3'

services:
    db:
        container_name: db
        image: postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
        env_file: 
            - project.env
    dj:
        container_name: dj
        build: DjangoBackend/
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - project.env
        volumes:
            - ./DjangoBackend:/code
        ports:
            - "8000:8000"
        depends_on: 
            - db

volumes:
    postgres-data: