// <auto-generated />
using System;
using BlazorBandNoodling.Server.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorBandNoodling.Server.Migrations
{
    [DbContext(typeof(BandContext))]
    [Migration("20190506215019_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview3.19153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorBandNoodling.Shared.Models.Enrollment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EnsembleID");

                    b.Property<int?>("Grade");

                    b.Property<int>("InstrumentID");

                    b.Property<int>("PartAssignment");

                    b.Property<int>("StudentID");

                    b.HasKey("ID");

                    b.HasIndex("EnsembleID");

                    b.HasIndex("InstrumentID")
                        .IsUnique();

                    b.HasIndex("StudentID");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("BlazorBandNoodling.Shared.Models.Ensemble", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Ensembles");
                });

            modelBuilder.Entity("BlazorBandNoodling.Shared.Models.Instrument", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsPersonal");

                    b.Property<string>("Make");

                    b.Property<string>("Model");

                    b.Property<string>("Notes");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<decimal>("PurchaseValue");

                    b.Property<string>("Serial");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("BlazorBandNoodling.Shared.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MNumber");

                    b.HasKey("ID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("BlazorBandNoodling.Shared.Models.Enrollment", b =>
                {
                    b.HasOne("BlazorBandNoodling.Shared.Models.Ensemble", "Ensemble")
                        .WithMany("Enrollments")
                        .HasForeignKey("EnsembleID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BlazorBandNoodling.Shared.Models.Instrument", "Instrument")
                        .WithOne("Enrollment")
                        .HasForeignKey("BlazorBandNoodling.Shared.Models.Enrollment", "InstrumentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BlazorBandNoodling.Shared.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
