# Generated by Django 2.2.2 on 2019-06-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Noname Jones', max_length=255),
        ),
    ]
