# Generated by Django 2.2.2 on 2019-06-06 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter an M followed by 8 digits', regex='[Mm]\\d{8,8}')])),
            ],
        ),
    ]
