# Generated by Django 2.2.1 on 2019-06-14 15:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_owner', models.ManyToManyField(blank=True, related_name='owners', to='bands.Student')),
                ('previous_owners', models.ManyToManyField(blank=True, related_name='previous_owners', to='bands.Student')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vendor', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bands.Asset')),
                ('kind', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('uc_tag_number', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Tag numbers take the format of 1-2 capital letters followed by 1 or more digits', regex='[A-Z]{1,2}\\d+')])),
                ('uc_asset_number', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
            ],
            bases=('bands.asset',),
        ),
        migrations.CreateModel(
            name='MaitenanceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('service', models.TextField()),
                ('invoice_number', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('combination', models.CharField(max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bands.Asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bands.PurchaseInfo'),
        ),
    ]
