# Generated by Django 2.2.3 on 2019-11-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_auto_20191011_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='kind',
            field=models.CharField(choices=[('Alto Clarinet', 'ALTOCLARINET'), ('Alto Saxophone', 'ALTOSAXOPHONE'), ('Baritone Saxophone', 'BARISAXOPHONE'), ('Baritone', 'BARITONE'), ('Bass Clarinet', 'BASSCLARINET'), ('Bass Trombone', 'BASSTROMBONE'), ('Bassoon', 'BASSOON'), ('Clarinet', 'CLARINET'), ('Cornet', 'CORNET'), ('Eb Clarinet', 'EFLATCLARINET'), ('Electric Piano', 'ELECTRICPIANO'), ('Electric Violin', 'ELECTRICVIOLIN'), ('Euphonium', 'EUPHONIUM'), ('Flute', 'FLUTE'), ('French Horn', 'FRENCHHORN'), ('Marching Horn', 'MARCHINGHORN'), ('Mellophone', 'MELLOPHONE'), ('Oboe', 'OBOE'), ('Piano', 'PIANO'), ('Piccolo', 'PICCOLO'), ('Soprano Saxophone', 'SOPRANOSAXOPHONE'), ('Sousaphone', 'SOUSAPHONE'), ('Tenor Saxophone', 'TENORSAXOPHONE'), ('Trombone', 'TROMBONE'), ('Trumpet', 'TRUMPET'), ('Tuba', 'TUBA')], default='Alto Clarinet', max_length=100),
        ),
    ]
