# Generated by Django 2.2.3 on 2019-07-30 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_auto_20190726_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['student__user__full_name']},
        ),
        migrations.AlterModelOptions(
            name='ensemble',
            options={'ordering': ['term', 'name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__full_name']},
        ),
    ]
