# Generated by Django 2.2.3 on 2019-11-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_auto_20191105_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('new', 'new'), ('good', 'good'), ('fair', 'fair'), ('poor', 'poor'), ('bad', 'bad'), ('unusable', 'unusable')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='kind',
            field=models.CharField(choices=[('Alto Clarinet', 'Alto Clarinet'), ('Alto Saxophone', 'Alto Saxophone'), ('Baritone Saxophone', 'Baritone Saxophone'), ('Baritone', 'Baritone'), ('Bass Clarinet', 'Bass Clarinet'), ('Bass Trombone', 'Bass Trombone'), ('Bassoon', 'Bassoon'), ('Clarinet', 'Clarinet'), ('Cornet', 'Cornet'), ('Eb Clarinet', 'Eb Clarinet'), ('Electric Piano', 'Electric Piano'), ('Electric Violin', 'Electric Violin'), ('Euphonium', 'Euphonium'), ('Flute', 'Flute'), ('French Horn', 'French Horn'), ('Marching Horn', 'Marching Horn'), ('Mellophone', 'Mellophone'), ('Oboe', 'Oboe'), ('Piano', 'Piano'), ('Piccolo', 'Piccolo'), ('Soprano Saxophone', 'Soprano Saxophone'), ('Sousaphone', 'Sousaphone'), ('Tenor Saxophone', 'Tenor Saxophone'), ('Trombone', 'Trombone'), ('Trumpet', 'Trumpet'), ('Tuba', 'Tuba')], default='Alto Clarinet', max_length=100),
        ),
        migrations.AlterField(
            model_name='uniformpiece',
            name='kind',
            field=models.CharField(choices=[('jacket', 'jacket'), ('pants', 'pants')], default='jacket', max_length=6),
        ),
    ]
