# Generated by Django 2.2.2 on 2019-06-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_auto_20190613_1958'),
        ('bands', '0002_auto_20190614_1518'),
    ]

    operations = [
    ]
