# Generated by Django 3.0.6 on 2020-05-14 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_auto_20191110_0123'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='maintenancereport',
            name='unique_invoice',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseinfo',
            name='unique_invoice',
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='purchaseinfo',
            name='asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='bands.PurchaseInfo'),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='assets',
            field=models.ManyToManyField(blank=True, null=True, related_name='maintenance_reports', to='bands.Asset'),
        ),
        migrations.AddConstraint(
            model_name='maintenancereport',
            constraint=models.UniqueConstraint(fields=('vendor', 'invoice_number'), name='maintenancereport_unique_number_for_vendor'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinfo',
            constraint=models.UniqueConstraint(fields=('vendor', 'invoice_number'), name='purchaseinfo_unique_number_for_vendor'),
        ),
    ]
