# Generated by Django 2.2.2 on 2019-06-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_merge_20190617_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('service', models.TextField()),
                ('invoice_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_info',
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bands.Asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_owner',
            field=models.ManyToManyField(blank=True, null=True, related_name='owners', to='bands.Student'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='previous_owners',
            field=models.ManyToManyField(blank=True, null=True, related_name='previous_owners', to='bands.Student'),
        ),
        migrations.DeleteModel(
            name='MaitenanceReport',
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bands.Asset'),
        ),
    ]
