# Generated by Django 3.0.6 on 2020-05-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_auto_20200513_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereport',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='maintenance_reports', to='bands.Asset'),
        ),
    ]
