# Generated by Django 2.2.2 on 2019-06-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_auto_20190618_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_owner',
            field=models.ManyToManyField(blank=True, related_name='owners', to='bands.Student'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='previous_owners',
            field=models.ManyToManyField(blank=True, related_name='previous_owners', to='bands.Student'),
        ),
    ]
