# Generated by Django 2.2.2 on 2019-06-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_auto_20190618_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='current_owner',
            new_name='current_owners',
        ),
    ]
