# Generated by Django 2.2.2 on 2019-07-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_auto_20190618_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniformPiece',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bands.Asset')),
                ('kind', models.CharField(choices=[('jacket', 'JACKET'), ('pants', 'PANTS')], default='jacket', max_length=6)),
                ('size', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
            ],
            bases=('bands.asset',),
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='condition',
        ),
        migrations.AddField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('new', 'NEW'), ('good', 'GOOD'), ('fair', 'FAIR'), ('poor', 'POOR'), ('bad', 'BAD'), ('unusable', 'UNUSABLE')], default='new', max_length=10),
        ),
    ]
