# Generated by Django 3.0.6 on 2020-05-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0009_auto_20200528_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='type',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Maintenance', 'Maintenance')], default='Purchase', max_length=20),
        ),
    ]
