# Generated by Django 2.2.3 on 2019-07-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0009_auto_20190703_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='locker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='bands.Locker'),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainenance_reports', to='bands.Asset'),
        ),
        migrations.AlterField(
            model_name='purchaseinfo',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_info', to='bands.Asset'),
        ),
    ]
