# Generated by Django 3.0.6 on 2020-06-25 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0010_auto_20200528_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensemble',
            name='is_active',
        ),
        migrations.AddField(
            model_name='ensemble',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
