# Generated by Django 2.2.3 on 2019-07-05 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0010_auto_20190705_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='vendor',
            field=models.CharField(default='Buddy Rogers', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseinfo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
