# Generated by Django 2.2.3 on 2019-07-12 18:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0011_auto_20190705_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='current_owners',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='previous_owners',
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='service',
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='asset',
            name='locker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bands.Locker'),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_reports', to='bands.Asset'),
        ),
        migrations.AlterField(
            model_name='purchaseinfo',
            name='vendor',
            field=models.CharField(default='Buddy Rogers', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='m_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter an M followed by 8 digits', regex='[Mm]\\d{8,8}')]),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(fields=('kind', 'make', 'model', 'serial_number'), name='unique_instruments'),
        ),
        migrations.AddConstraint(
            model_name='maintenancereport',
            constraint=models.UniqueConstraint(fields=('vendor', 'invoice_number'), name='unique_invoice'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinfo',
            constraint=models.UniqueConstraint(fields=('vendor', 'invoice_number'), name='unique_invoice'),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='members',
            field=models.ManyToManyField(through='bands.Enrollment', to='bands.Student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='assets',
            field=models.ManyToManyField(through='bands.AssetAssignment', to='bands.Asset'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='ensemble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='bands.Ensemble'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='bands.Student'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bands.Asset'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='bands.Enrollment'),
        ),
        migrations.AddConstraint(
            model_name='ensemble',
            constraint=models.UniqueConstraint(fields=('name', 'term'), name='unique_ensemble'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('ensemble', 'student'), name='unique_enrollment'),
        ),
    ]
