# Generated by Django 2.2.3 on 2019-07-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0012_auto_20190712_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='assets',
            field=models.ManyToManyField(related_name='enrollments', through='bands.AssetAssignment', to='bands.Asset'),
        ),
        migrations.AlterField(
            model_name='ensemble',
            name='members',
            field=models.ManyToManyField(related_name='ensembles', through='bands.Enrollment', to='bands.Student'),
        ),
    ]
