# Generated by Django 2.2.3 on 2019-07-23 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0013_auto_20190712_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='locker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='bands.Locker'),
        ),
    ]
